kernel: Drop duplicated object
* Breaks AOSP build.

ld.lld: error: duplicate symbol: apply_kernelsu_rules
>>> defined in drivers/built-in.a(kernelsu/selinux/rules.o)
>>> defined in drivers/built-in.a(kernelsu/selinux/rules.o)

ld.lld: error: duplicate symbol: handle_sepolicy
>>> defined in drivers/built-in.a(kernelsu/selinux/rules.o)
>>> defined in drivers/built-in.a(kernelsu/selinux/rules.o)

ld.lld: error: duplicate symbol: setup_selinux
>>> defined in drivers/built-in.a(kernelsu/selinux/selinux.o)
>>> defined in drivers/built-in.a(kernelsu/selinux/selinux.o)

ld.lld: error: duplicate symbol: setenforce
>>> defined in drivers/built-in.a(kernelsu/selinux/selinux.o)
>>> defined in drivers/built-in.a(kernelsu/selinux/selinux.o)

Change-Id: Icc313ea90b0df4b4e5210ac53ada5fba83269bba